version: 3

tasks:
  default:
    silent: true
    cmds: ["task -l"]

  .stow:
    requires:
      vars:
        - platform
      cmds:
        - stow {{ .platform }} -t $HOME --no-folding

  macos:
    desc: Run stow for macos
    cmds:
      - task: .stow
        vars:
          platform: macos
