version: 3

tasks:
  default:
    silent: true
    cmds: ["task -l"]

  .stow:
    requires:
      vars:
        - platform
    cmds:
      - stow {{ .platform }} -t $HOME --no-folding

  linux:
    desc: Run stow for linux
    cmds:
      - task: .stow
        platform: linux

  macos:stow:
    desc: Run stow for macos
    cmds:
      - task: .stow
        vars:
          platform: macos

  macos:init:
    desc: Init macos things
    cmds:
      - ./macos/init.sh

  macos:
    desc: Run macos:init and macos:stow
    cmds:
      - task: macos:init
      - task: macos:stow
