return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	config = {
		ensure_installed = {
			"efm",
			"lua-language-server",
			"stylua",
			"luacheck",
			"gopls",
			"terraform-ls",
			"volar",
			"eslint_d",
			"ts_ls",
			"helm_ls",
			"yaml-language-server",
			"yamllint",
			"prettier",
			"sqlls",
			"sqlfluff",
			"bash-language-server",
			"shellcheck",
			"shfmt",
		},
	},
}
